version: '3'
services:
  database:
    container_name: foodtosave-nestjs-test-db
    image: postgres:14
    environment:
      - 'POSTGRES_DB=food-to-save-nestjs-test'
      - 'POSTGRES_USER=test'
      - 'POSTGRES_PASSWORD=test'
    ports:
      - '5429:5432'
  redis:
    container_name: foodtosave-nestjs-test-redis
    image: redis:7
    ports:
      - '6377:6379'
