version: '3'
services:
  database:
    container_name: foodtosave-nestjs-db
    image: postgres:14
    environment:
      - 'POSTGRES_DB=food-to-save-nestjs'
      - 'POSTGRES_USER=test'
      - 'POSTGRES_PASSWORD=test'
    ports:
      - '5431:5432'
  redis:
    container_name: foodtosave-nestjs-redis
    image: redis:7
    restart: always
    ports:
      - '6372:6379'
  api:
    container_name: foodtosave-api-nestjs
    image: foodtosave-nestjs
    depends_on: [database, redis]
    environment:
      - DATABASE_URL=postgresql://test:test@database/food-to-save-nestjs?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_TTL=10
    ports:
      - '3000:3000'
